### ISSUE TITLE
hunt-server-0.3.0.2 doesn't compile with GHC 7.8.4

### ISSUE THREAD

**Issue by peti** [hunt-framework/hunt#99]
Citing from http://hydra.cryp.to/build/606753/log/raw:

    Building hunt-server-0.3.0.2...
    Preprocessing executable 'hunt-server' for hunt-server-0.3.0.2...
    <command line>: can't decode size: -rtsopts

**Comment by chrisreu** [comment]
I just built the server with GHC 7.8.4 on my machine without any problems. Also, I've never seen that particular error message before. 

When looking for that error message, i only find it in older GHC version like 7.6.3:
https://downloads.haskell.org/~ghc/7.6.3/docs/html/libraries/ghc-7.6.3/src/StaticFlagParser.html

In GHC 7.8.x, that module seems to be gone and merged into another one, according to:
https://ghc.haskell.org/trac/ghc/ticket/7595

I cannot find the error message in GHC 7.8.4 sources at all, so that is confusing me a little. It is definitely not a general error concerning 7.8.4. Maybe you find some hints to your problem within the ticket?

**Comment by peti** [comment]
Have you tried building the package with `runhaskell Setup.hs configure && runhaskell Setup.hs build`  instead of relying on `cabal-install`?

**Comment by alexbiehl** [comment]
Same for me. 

The particular code is located here in GHC HEAD: https://github.com/ghc/ghc/blob/8a5d32057fb899810d5fb614e57a319b4a951afc/compiler/main/DynFlags.hs

But it does not seem very different from 7.6.3 sources.

**Comment by peti** [comment]
The problem is the `-H` flag, IMHO, because it lacks a size argument:

    -H<size> Sets the minimum heap size (default 0M)   Egs: -H24m  -H1G

Generally speaking, it feels problematic to hard-code flags for the run-time system into the Cabal build.

**Comment by chrisreu** [comment]
Thanks for the input. I'm not sure right now, what the reason for this was. Seems to be necessary for the statsD flag, but if installed without that flag, i guess we could/could remove that run-time information.

@sebastian-philipp What do you think? (b6a9ed3f1ccb4f801eb930fb6ccd18b57266ccfb)

**Comment by sebastian-philipp** [comment]
ja. May not be such a good idea to put them into the cabal file. These RTS flags are system dependent anyway. Maybe we should move these settings to Hayoo and remove them from this repo.
